CodingTrain/Rainbow-Poem

poem.txt

A small prince contribution

---

poem.txt

Red is hot

---

poeme-francais

Here is a simple french translation of the Rainbow poem.

french translation

---

poem.txt

not sure, if this went out twice (sorry if it did!)—best regards, and have a cup of oolong tea some time!

Hey, I named the pony and gave it some tea

---

poem portuguese.txt

I just added a portuguese version for the rainbom poem

Portuguese version

---

poem.txt

Updating the unicorn to a rainbow coloured unicorn.

Updating the unicorn

---

poeme-francais

le date de up en un le grand champignon poetic du rivage solitude

le révision de la pomme

---

poem.txt

Because blue + green = teal, which is why it's my son's favorite color!
It's teal. You can't say no to teal!

Added teal!

---

poem-deutsch.txt

Poem in german

---

poem.txt

Adding  East or West Dannie is the best!.

This fixes the issue #23.

---

poem portuguese.txt

Adding some parts and updating syntax

Syntax update

---

poem-deutsch.txt

Fixed a wrong written word in line 19.

---

poem.txt

Can't forget the color brown in relations to Earth Day. ~

I added brown!

---

poem.txt

Updated green line

---

poem-deutsch.txt

"Recycle" wasn't grammaticly correct in the german language, and I changed the last line (that wasn't empty) to something that makes sense and conforms to the english version.

Grammar & Meaing improvements

---

poeme-francais

In original poem.txt by Daniel Shiffman, there was the word "recycle" after indigo. Since "poeme-francais"  seems to be a french version of poem.txt, I added the translation of "Recycle" in french, which is "Recycler" #32

I added a french translation of recycle

---

poem.txt

I Added the follow description for the color Yellow
"The color of the best-known plasma sphere"
Could you please merge this with your document

I addd a description for the color Yellow

---

poem.txt

Please I really think you deserve your own verse ;)

Hey I added the 24th verse

---

poem.txt

I think clouds might be better here.
It's more poetic ;)

Adding clouds as per #36

---

poem.txt

adding rainbow in NYC

---

poem.txt

Adding let's dance as per #39

---

poem-dutch.txt

I thought it would be important for everyone to understand this beautiful piece of poetry, so I translated it to Dutch.

Created a Dutch version of the poem

---

poem.txt

Adding more to this lovely poem

Adding purple Reign

---

poem.txt

I added the conclusion for this poem

---

poem.txt

Adding the initial coordinates for the Rainbow extended description

Adding the initial coordinates fixes #47

---

poem.txt

Also added quotes to attribute the saying of "I love Earth Day." to Peter Pony.

Change "he" to Peter Pony in line 4

---

poem portuguese.txt

verse added
"Pôneis correm acima dos arco-íris."

adding new verse to the portuguese poem

---

poem.txt

love the videos! They help alot!

added a line about unicorns

---

poem.txt

Fairies are real!

---

poem-italian

adding italian version

---

poem.txt

Hello Governor - Please accept my pull request : )

Added line 42

---

poem.txt

Spent 4-5 years in Tokyo and not seen a rainbow yet. I'm a bit bewildered by this.

Line 43 added

---

poem.txt

Please add my comment so u can know I love ur vids

I added Love ur vids

---

poem.txt

updated poem

---

poem.txt

Pot of gold
Box of Lucky Charms

added pot of gold and lucky charms

---

poem.txt

Thank you for a great tutorial!

Added "Pony of poets" at the end

---

poem-italian

"Coordinate" was mispelled in the italian version. 
I love the idea github for poets.

Changed mispelled "cordinate" to "coordinate"

---

poem.txt

Added "Hamburgers dancing at the Meatball!!"

 This fixes #89

---

poem.txt

Just Starting out with Git and GitHub ! 
LOVE your videos! 
U r the best!

added line "The crumbling cookie!"

---

poem.txt

Updated poem.txt to reflect today's date until a better solution can be found #96

Updated to reflect today's date #96

---

poem.txt

The assertion that unicorns exist should be qualified as either having a trait of multi-dimentionality, or in some far away land that's hard for most people to reach as I have not seen any unicorns lately.

Unicorns Are Scarce.

---

poem.txt

Say no to grass lawns. And thanks for your videos! :)

Adding Lawn Conversion

---

poemaPT

from portugal

---

poem.txt

Today is Thursday 
b0f697fc47a934c416f2a9f4c27bd69f35a5ddba resolves issue #107

added Keep Calm and Carry On!

---

poem portuguese.txt

added Hello

---

poem.txt

Poems typically rhyme. Eagerly awaiting pull response!

Added rhyming words

---

poem.txt

fixes issue #121

---

poem-indonesian

In this file i write color name in Indonesian Language

I added a file that called poem-indonesian

---

poem-indonesian.txt

Adding poem and testing pull request

Adding poem-indonesian

---

poem.txt

an extremely wonderful line was added c:

a line was added xd

---

poem-italian
poem-vietnamese

your teaching style is so cool.
can we add the vietnamese version for the poem?

I care about the Earth Day too

---

poem.txt

This is cool!

---

Spring-Now
poem-chinese.txt
poem.txt

i have just watched your video,and i think it's really great.

Hello world

---

sweden.txt

Hello! I added sweden.txt :)

---

Cambodia.txt

Hello from Cambodia.

---

poem.txt

Details of Ponies and Unicorns

Added details about Ponies and Unicorns

---

poem-chinese.txt

Adding some Chinese verse followed with
my translations.

Adding some Chinese verse

---

Poem-India

I really appreciate what you do... Thank you so much

Hey I have added a new paragraph

---

BG

Another test

---

poem-arabic

this fixes #187

---

poem.txt

Adding sunny skies, removing love of thursdays.

Adding sunny skies

---

poem.txt

thank you so much for this tutorial.
love from india. :)

Hey !! i'm loving this 

---

poem.txt

Updated poem.txt with more poem!

---

poem.txt

Ai Lad, Unicorns are marvelous!!

added a touch of Yorkshire at line 96

---

poem.txt

Added a line from Queen's Bohemian Rhapsody

---

poem.txt

Could you please add a small poem from Charles Chaplin ?
Thank you !

Hello, I've added Charles Chaplin poem

---

poem.txt

Thanks for such an awesome tutorial.
You're teaching style is great! :D

Added thank you note in line 5

---

_config.yml
poeme-francais

I am adding Chocolate in the french version of this poem

---

poem.txt

This Fixes #216

---

poem.txt

purple rain
I only wanted to see you
Bathing in the purple rain

adding a piece of lyrics about 'purple rain'

---

poem.txt

learning github, thanks for the lessons!

added lines 102-105

---

poem.txt

Setting things straight

---

poem.txt

Just adding my two cents... don't worry I borrowed it from a gas station counter!

My 2 cents

---

poem-deutsch.txt

Zikaden (Auchenorrhyncha ) are insects

Added description about Zikaden

---

poem-1337.txt

English has been translated to 1337 speak.

Added a 1337-speak version of the poem

---

poem.txt

this fixes #229

---

Poem-India

Please accept my 1st pull request.

Added one line to India Poem

---

Poem-India

hello.
I am an indian so added a few cool lines to the Indian poem!
Hope it heps 
:+1:

Added a few more interesting lines

---

poem.txt

adding new line into the poem to check if works

---

poem-chinese.txt

my first pull request, comment on poem-chinese.text

comment on poem-chinese.txt

---

luckyCharms

Added a poem about rainbows and Lucky Charms cereal to the newly created Cereal branch

Lucky Charms cereal

---

Poem-India

`sole` should be `soul` :wink:

Update Poem-India - moderate priority

---

poem.txt

I had to add a line about being thirsty and how it changes you as a person. To the core.

I added line about being thirsty

---

poem.txt

Capital and grammar corrections

---

poem.txt

Please accept my request. I love my country.

adding Filipino text

---

poem.txt

I am following your learning tutorials "A2Z" and just wanted to learn Pull Requests.

adding a line in poem.txt

---

poem.txt

more serbian text added per #759

---

poem.txt

issue test #744

---

poem.txt

first pull request, made the poem considerably more rainbow-y

Contribution to Poem.txt

---

test

i am adding a new test

---

poem-fork.txt

Created poem-fork

---

poem-Nepali

Hello! Hope it gets merged. Thanks

created a poem from nepal.

---

Romanian poem

Create Romanian poem

---

love_rainbows.txt

This is a follow up of the youtube video on creating pull requests. Please pull the changes and let my love for Rainbows be reflected in the original Rainbow Poem repo.

Expresses love for Rainbows

---

kannada-poems
poem.txt

calling people to add new poems

created kannada poems file

---

sleep

A poem about sleep, or lack thereof

Created new Poem

---

Tagalog na Tula.txt

Hi Dan. I'm a fan from the Philippines. 👍

created a Filipino poem

---

practise

practicing creating a pull request

I watched the video and is practicing

---

practise

Recycleadded

---

last-poem-that-you-would-want-to-read

As a first time poem writer I think I've done a better job in writing a piece. Please pull my wonderful creation into your main git repo.

Added a poem, that's written a bit differently. 

---

Heartbeat

Another poem for the collection :)

Heartbeats and Poems 

---

poeme-francais

I added 2 nice verses to that poem with a little moral.
Ajouté deux petits vers et une morale comme tout poème qui se respecte.

Ajouté deux vers

---

poem.txt

I feel that horses are often overlooked when compared to ponies

Hey I added a horse harpist reference

---

poem.txt

Added myself

---

poem-filipino.txt

i added a filipino poem from Jose Corazon de Jesus.

add filipino poem

---

poem-myanmar

Please consider to add a short Burmese poem :D

Poem from Myanmar (Burma)

---

poem-deutsch.txt

Please add my new farys to the german version of the poem.

Added 2 Good Farys

---

poem-italian

Hey, i add some italian words on poem italian file..just to test my pull-request skill :D 
Cheers!

Added new words on poem italian

---

Nature Poem

Just adding some lines to you poem nothing much

Nature poem

---

JS_Poem.md

I wrote a writing about JavaScript and my journey from not knowing, to knowing. Now I have knowledge and I know it.

I wrote a writing about learning JavaScript

---

Poem-India

add it , i love rainbows soo much :D :D :D

changes made :D to Poem-India

---

poem.txt

i used this name because its just an obvious name

i added June 14 2018 change

---

indonesian-poem.txt

This is the best poem i ever made with all of my heart.
Best Regard,
Indonesian Poetry Club.

Hey Shiffman! I added new Indonesia Poem.

---

poem portuguese.txt

So, this is my proposal to add "boto" to the list! It is pink and incredible.

Added animal to the list as per Issue #707

---

poem.txt

Updating the master using pull request function

Update original poem.txt from CodingTrain

---

Poem-learner.txt

my version of poem

---

poem.txt

added one more unicorn

---

test

recycler recycler meme les poemes sont a recycler

i just wanna test The fork

---

poem-polish.txt

There was no polish version of the poem so I made it.
Keep up the great work!

Hey i added a polish version of your poem

---

BG

Your tutorial is really great. Thanks!

Please accept my first commit to this repository

---

ThePoem-coffee

Poem about food

---

rainbowtale.txt

Let's write a great story about rainbows and unicorns and get rich! ;)

This is a new tale about the Rainbow and the Unicorn

---

coder_poem

let **accessGranted**:bool = Bool()
if(**accessGranted** == true){
\\Pull accepted 😎
}else{
\\Pull denied 😱
}
//_Thank you enjoyed your video_

Swift Coded Poem

---

poem.txt

added a flower reference

---

Cambodia.txt
poem_marathi.txt

Written and Directed by Sanjay Leela bansali. Best form of marathi poetry, read and admired by millions of Indians.

essential Marathi poem

---

Assamese Poem

Hey, I am fan of yours(tutorials) from Assam, India.
Hope you will love to add the poem.

Added an  Assamese Poem

---

desanka-poem.txt

I apologize for not writing the poem on English but it would lose its meaning and anyway its for practice purposes only.

I added a poem from a renowned poet Desanka M.

---

luckyCharms
poem.txt

I added the thought...'what if rhinos are actually fat unicorns?' 🤔 🤔

Rhinos and unicorns

---

README.md

Just for Your hard work

---

poem.txt

you know, I love the rainbows so I have added some more of them <3 <3
#338

Added some more rainbows

---

poem-chinese.txt

fixed typo in poem-chinese.txt

fixed a typo!

---

poem.txt

add Tashi Delek

---

BG

Add another line

---

README.md
poem-arabic
poem.txt
practise

updated poem.txt

---

poem-arabic

this fixes #366

---

NewRequest

Thanking you for the GitHub videos.

My fist Pull Request

---

poem portuguese.txt

New line added: "Todos saem para comemorar" in the portuguese version of the poem.

New line at the beginning

---

poem.txt

came from the github tutorial on youtube! it was really helpful

added a line about the color pink

---

luckyCharms

What do you think? good answer?

answer to whom gets the pot of gold

---

poem.txt

Once again, thanks for this!

---

three-sixty-five

a poem about a coding challenge

three-sixty-five

---

test.txt

test adding a file to a branch then making a pull request

test adding a file

---

README.md

A contribution from SP Brazil

---

poem.txt

added text on line 243

---

favoriteThings.txt

I am a little sad today so I made a list poem of things that make me happy

Added favoriteThings.txt

---

Poem-India

Added my feed back

---

poem.txt

Hot shiffman poem around line 244

Adding a cool shiffman poem

---

poem-markdown.md

Update poem-markdown.md closes #396

---

Cambodia.txt

Hi I added thanks

---

BG

Just learning, folowing tutorial

Hey! I added one line

---

ros-poem.txt

Add ros-poem

---

Poem-India

this poem represent true INDIA.

---

BG

this is nebil from los angles

---

testashok

New file added

---

poem.txt

Adding the beautiful color of Gold to the List

This fixes #427

---

adding-complexity

Adding Complexity

---

poem.txt

Added 90's alt rock reference, fixes issue #433

---

poem.txt

Thanks for the GitHub for Poets! You are a scholar and a gentleman. Keep up the good fight.

Hi, added a small couple of couplets at the end

---

rainbow_in_german.txt

Deutsch ist auch eine Sprache.

Create file rainbow_in_german.txt

---

Germany is nice

This adds a small poem about **Germany**

Something 'bout germany

---

poem.txt

Adding one new line to poem.txt

---

A poem on Rainbow
BG
Cambodia.txt

I had seen your video and from there i got the link to this repository and then i decided to practically do this here on git hub.

Please accept my pull request. 

---

Abracadabra boom boom go

please accept this pull request which will close my issue and also please accept #448 .

this resolves the issue #449 .

---

rainyday.txt

thanks for your video tutos they are really useful and this is my 1st pull request.

just made a none sens poem of rainy day & rainbow

---

poem.txt

Added a heart

---

poem.txt

Added a verse
A little late to the party but better late than never i guess :)

Fixed a few grammatical errors

---

poem.txt

I added some Serbian poem lines into the original poem. :)

Adding serbian ranbow poet lines

---

poem.txt

Check out this observation I made

Hey I added some observations about the poem

---

poem-arabic

The English Translate for The Arabic Words.

---

practise

hi, i hope it's ok i just added a line!

---

poem-indonesian.txt

Added the unique Indonesian laughter

---

README.md
zalles_rp

here is my poem!

---

poem.txt

Hi just added my intro and i love this session

just added my intro

---

Poem-India

I wanted to contribute too after I saw your video but I didn't had any great idea.
So, I thought that I can do this...
I added "I love India" in Poem-India.

Being a little patriotic ;)

---

Poem-India

changed the spelling from enloy to enjoy at line no 11

Indian poem..

---

A NEW FILE.TXT
README.md
Rainbow-Poem-Chinese

O(∩_∩)O hello,world, this is from china

---

poem.txt

Very very thank you for your tutorials.. :)

Adding a quote

---

poem-arabic

say Hi in Arabic

---

poem.txt

For all the visual learners out there.

Added rainbow ASCII art

---

Poem-India

i am adding some more rhymes to the poem, the poem was already good but i just wanted to add some more lines to it to make it more like a lyrical thing. I have tried, check this out and if you find it good accept my pull request :)

adding some new rhymes to a nice poem!

---

poem.txt

Practice. Thanks for the repo. :)

Hey, I added Update Poem.txt.

---

poem.txt

Added stuff about cake

---

Poem-India
poem-spanish.txt

Add poem-spanish

---

poem.txt

Added Hello Comment to Poem.txt 
Just out here, learning github..

Added Hello Comment to Poem.txt 

---

poem.txt

Please accept my changes
[click me](url) **YAY for Unicorns**

Fix for #94

---

poem.txt

I am really thinking about Monday and how much I hate Mondays today

Hey I added Monday

---

poem.txt

Added Line

---

poem.txt

Added learning GIT lines

---

Poem-India

Hey I did that

---

poem-lithuanian.txt
poem.txt

Added lithuanian poem

---

poem.txt

Hi please add my comment

---

polish-poem.txt

Hi! I write a masterpiece for you! Greetings from Poland!!! <3

POLISH-POEM

---

poem.txt

I would like to try unicornbread if it exists

Hi, I would like to add this unicornbread poem

---

poem-deutsch.txt

correcting 'Recyclen' typo to 'Recyceln'

---

BG

i am really thinking about the earth and how much i love.

hey i added recycle 

---

coder_poem

My code is good

---

BG

this should fixes #616

---

poem.txt

Thanks for your great videos.  👍

Some small updates

---

poem.txt

Add to poem.txt

---

poem.txt

adding my contribution

---

poem.txt

No more violence against tress

This fixes #651

---

poem.txt

Hey ,  I added a new line ;}

---

poem.txt

Please add my pull request!!! <3

Added poem to poet.txt

---

luckyCharms

Lucky charms sounds amazing. I will try them if I can find some in local shops :)

I added few verses to this cool poem

---

poem.txt

pontificating on double rainbows and their double enjoyment

adding double rainbows

---

poem.txt

Added english translation for Paolo Coelho quote

English translation in poem.txt

---

poem.txt

Fixed #782

---

Sample Rainbow File

Tryin' out some stuff here. Please accept my pull request. Thank you!

Adding the first line

---

Chicago
test
yolo.txt

This is to test how I really learned from the tuts

Hey, I added some stuff 

---

poem.txt

I would love to see some text of mine placed in the poem.text file
Thanks

I am adding some text

---

Forking poem

Update Forking poem

---

poem.txt

Practicing YouTube video tutorial.

hello! added recycle!

---

Moroccan rainbow poem.txt

please pull my peom, and thank you for the sweet videos.

Hey I added Moroccan rainbow poem

---

russian poem

hi from Russia!

---

Dead Poets Society

nothing meaningfull but somethin'

Adding something

---

Turkish Poem

By the way, you are awesome. I am a real fan of you!

This fixes #836

---

poem - India.txt

Creating India Poem

---

truth-about-cats

New evidence has been found!

---

LateLament.txt

This is a poem that is featured in the end of the album Days of Future Passed.

Adding a poem by Moody Blues

---

StarWars.txt

Add poem do or do not fixes #843

---

poem-chinese.txt

My first time using pull request. Thanks to The coding train!

Added few interesting lines

---

Cambodia.txt

I have added that I am awesome.

---

rainbow-català

segundo request

---

poem.txt

Please add it, it is cool line

Added new Line

---

Forking poem

Add my lines

---

BG

My first contribution.

---

Wisdom

Birds of a feather flock together!

Old wisdom!

---

love

Fixes #889

---

Chicago

Adding voilet color to rainbow

Adding violet color

---

poem.txt

Simple Edit to poem.txt

---

poem-Nepali

Visit Nepal

---

coder_poem
myRainbow

Dave arrives

---

poem.txt

133713371337133713371337133713371337133713371337133713371337133713371337

Hey I added 1337

---

Cameroon

After following your tutorial on git and GitHub, I decided to participate. Hopefully, I did things right enough to have the commit accepted.

Hey. I added a file Cameroon

---

BG

Added a line with thank you msg

Just checking the pull request feature

---

Poem-India

2 lines added

---

test

NEw addded

---

poem.txt

Please merge it. I am new to GitHub. It's 2018.. Still getting pull requests...HAHA!!!!!!!!! Thanks!

Hey I add a new line to poem.txt

---

poem.txt

I think Earth Day is a happy day because it makes everyone happy :)

Hi I added Happy Earth Day

---

Bangladeshi poem

Update Bangladeshi poem

---

Mother-Poems

Hi Guys created a new poem on my mom.

created mom poems

---

Poem-India.txt

this is a file being added. Some of the famous poems of india.

add Poem-India.txt file

---

Love Rainbows

I like rainbows after rain so much

Create Love Rainbows

---

poem.txt

Hey I added title/description

---

poem-telugu.txt

Hi i have added poem  telugu language please add it to main branch.
thank you

poem-telugu.txt added - telugu language poem

---

poem.txt

Added p5 and processing to the first "poem" of colours by jandrocamus

Add p5 and processing

---

Chicago
Thank you

Thank you note to Coding Train for his YouTube tutorials!

Thank you note

---

GIT-Term-Poem.txt

Longer form poem based on the goals of the "1.1: Introduction - Git and GitHub for Poets" Coding Train video tutorial.

Based on 1.1: Introduction - Git and GitHub for Poets

---

Poem-India

Update Poem-India.This fixes issue #963

---

Maggie Poem

Hey CodingTrain,
I added this maggie poem.
Check it out if you also love eating maggie.

Maggie Poem

---

dolphines and trains

Adding my own poem to the collection. ...meh.. I am presenting my newest creation! The Dolphines and Trains poem!*

Dolphines and Trains poem

---

poem-chinese.txt

fixed #978

---

Poema del Arcoiris

Esta es una prueba en forma de contribucion y agradecimiento.

Poema del Arcoiris

---

love_rainbows.txt

I check your tutorial and added something for practice.

i added little 

---

BG

please accept my req so  i can learn how to use github properly

updated bg

---

Chicago

Though there should be a line about season changes

Hey I added season change

---

.github/pull_request_template.md

Thanks for starting this @akraus53!
I confirm that

Some edits to the pull request template

---

Japanese poem

upgrade done

---

freecodecamp

I really believe programming is poetry, but can also be a fight. An allusion to Braveheart, "We fought like warrior poets." Please accept, if changes are acceptable. Also, I'm just trying to learn github and pull requests, etc.

Added warrior theme

---

Bangladeshi poem
River Poem

The coding train railway :) I hope I don't get derailed

The coding train railway :)

---

kashmir_heaven_on_earth.md

Hi Dan!!!
Hope you are good.
I have added a file, It's speaks about my home land! Which is no less than a Paradise on earth.
Please merge!

Paradise on Earth

---

poem-coffee

Please I am thinking about github with coffee!

Hey I added github in coffee

---

poem-norwegian

"Gradiosa pizza" should be in one word, thats how norwegian work.
I also added a header.

Fixed typo

---

ilyCP.txt
kannada-poems

added a reply

---

.github/workflows/greetings.yml

Setting up messages for first issue and pull request. Open to suggestions and better wording. Could alternatively include a message in the pull request and issue templates.

Greeting Message with Actions

---

Pasta Rainbows

from Italy with pasta.

---

Indian Poem

I have added an Indian poem and created a pull request for it. 
Please accept my pull request.

Indian Poem added

---

poem-coffee

i thought it drives the poem home

he i added the last line 

---

Hi from Hungary

Added my little poem :>.
Thank you for your guidance.

Added a little poem from Hungary

---

practise

Added York

---

xlincw0w

Hello shiffman

---

Python poem.txt

Added a thoughtful poem about python

Create Python poem.txt

---

Dead Poets Society

Update Dead Poets Society

---

Dead Poets Society

Hey, I added another famous quote from The Dead Poets Society Film

---

poem.txt

added a small poem to the beginning

---

README.md

Thank you message

---

Chicago Poem

Update Chicago Poem

---

dogs.txt
poem.txt

continuing the prime directive

adding funtimewow

---

poem.txt

now it should work and close my issue automatically

this is a fixes for #1078

---

Poem-learner.txt

Add the line to poem fire golden unicorns. Please let me know what you think about this line?

Added line With fire golden unicores

---

AlgerianCitation

I decided to contribute to the project by adding something of our countrie's citations

Hey I added an algerian citation

---

poem.txt

my first opull request

---

Rainbow

Dont be a fool

---

Forking poem

Update Forking poem test

---

poem.txt

please accept my pull request
i'm just starting to learn GitHub
Greetings from German Rainbows ;o)

Greetings from German Rainbows

---

poem.txt

I really want to thank you for teaching this brilliant tech!

Hey  i added a thankyou note

---

beautifultest

Added a new poem, learning how to do a pull request is fun!

Added beautiful test - another poem

---

yolo.txt

added pull request 

---

george.txt

Thanks for a great series on YouTube! Loving the channel, keep up the good work!

Loving your Git/GitHub series - Subscribed

---

Poem Made of My Poem

Added Poem with MyPoem To the Poem File

Poem Made of my Poem

---

poem.txt

A not insightful but valid poem

Adding poem

---

README.md
rainbow pracise

i didn't saw any  rainbow gif so thought it might be something new

added a link to a rainbow gif

---

Poem-India

Added the beginner's ritual "Hello World!" to Poem-India

Added "Hello World!"

---

Uttar-Pradeshi Poem

I too am really thinking about earth and how much i love rainbows today . xD
Now here is an pull requested issue regarding #1133

Uttar-Pradeshi Poem added

---

Chicago

Thank you so much for your help

Hey, I added some lignes to test github

---

i-try.txt

Add my poem too

---

BG

edit white space line 9
added line 16

A few edits

---

JourneyPoem.txt

maybe my poem is not related with rainbow but i just trying to make my poem

Create my own poem

---

Rain-bow-ode.txt

Rainbows  are awesome. Here are a few reasons why. 
Also, love your channel CoderTrain! You have saved me so much time!

The ode to rainbows

---

myRainbow

added angry

---

Poem-India

add an stanza in poem where "Jai Ho!" is "Hailing" someone or something and here Jai Ho! Rainbow.. :) 
**Thanks to your videos I just started learning Github properly! :smile:

Add Jai Ho and Rainbow

---

poem-florida

Learned something about pull request today!

Florida-man

---

poem-deutsch.txt

I've added a waterfall

---

Poem-India

Came here from The Coding Train

Added a few lines on India and Pakistan

---

Dead Poets Society

Added "carpe Diem" on top of seize the day!

Updated of Dead Poet's society poem 

---

poem.txt

I did not see any Japanese text in the file, so I would like to add Japanese!

Hello. I added a Japanese text

---

Chicago

Thanks change to "Thank you" and moved to last line of the document.

Modification to Chicago file

---

Feedback

Simple edit for Pull Request

---

poem-chinese.txt

Adding comments in poem-chinese.txt

---

Cloud-Poem

Very essential complement for Rainbow-Poem

Add Cloud-Poem

---

khan.txt
toResolveIssue.txt

This is my first pull reuest.

---

Not a Poet

The following is for practice forking and pulling requests. 
Added five more verse to the file 'Not a Poet'.

Added five more verse to file 'Not a Poet'

---

poem.txt

Just another comment

---

Horse's
Tonda

Since You do not have an issue with this great poem i am closing your issue.

This fixes #1183
